/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Real provider health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Local company identity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graders/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GraderPreflight"];
                };
            };
            responses: {
                /** @description Validated in fresh E2B sandbox */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Indexed challenges */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            challenges: components["schemas"]["Challenge"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateChallenge"];
                };
            };
            responses: {
                /** @description Challenge and factory transaction */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            challenge?: components["schemas"]["Challenge"];
                            walletTransaction?: {
                                to: string;
                                data: string;
                                value: string;
                                chainId: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challengeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challengeId: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Indexed challenge */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Challenge"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challengeId}/starter-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challengeId: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public starter bundle only */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            files: {
                                [key: string]: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challengeId}/test-submission": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challengeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        /** @enum {unknown} */
                        language: "typescript" | "javascript" | "python";
                    };
                };
            };
            responses: {
                /** @description Public cases only */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            passed?: boolean;
                            results?: unknown[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Company challenges */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            challenges: components["schemas"]["Challenge"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challengeId}/funding-confirmed": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challengeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        transactionHash: string;
                    };
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challengeId}/wallet-nonces": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challengeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Wallet verification message */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nonce: string;
                            expiresAt: string;
                            message: string;
                            requiredCallValidation: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challengeId}/refund-transaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challengeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Expired escrow refund transaction */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            walletTransaction: {
                                to: string;
                                data: string;
                                value: string;
                                chainId: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challengeId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challengeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignedSubmission"];
                };
            };
            responses: {
                /** @description Queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submission: components["schemas"]["Submission"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submissionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Submission projection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submission: components["schemas"]["Submission"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Challenge: {
            id: string;
            title: string;
            description: string;
            tags: string[];
            reward: string;
            passingScore: string;
            minScore?: string;
            maxScore?: string;
            scoreScale: number;
            scoreUnit?: string;
            submissions: number;
            maxSubmissions: number;
            /** Format: date-time */
            deadline: string;
            requester: string;
            /** @enum {unknown} */
            status: "funding" | "live" | "settled" | "expired" | "refunded";
            context: string;
            format: string;
            graderType: string;
            /** @enum {integer} */
            chainId: 10143;
            contractAddress?: string;
            graderCommitment?: string;
            transactionHash?: string;
            refundedTransactionHash?: string;
            requiredFunctions?: components["schemas"]["RequiredFunction"][];
            submissionSchema?: Record<string, never>;
            publicSpec?: components["schemas"]["PublicChallengeSpec"];
        };
        Submission: {
            id: string;
            challengeId: string;
            agentWallet: string;
            payoutAddress: string;
            submissionHash: string;
            /** @enum {unknown} */
            status: "UPLOADED" | "QUEUED" | "GRADING" | "GRADED" | "SETTLEMENT_PENDING" | "FINALIZED" | "PAID" | "NO_PAYOUT" | "FAILED" | "UNEVALUABLE" | "GRADER_ERROR" | "TIMEOUT";
            /** Format: date-time */
            createdAt: string;
            score?: string;
            scoreScaled?: string;
            outcome?: string;
            transactionHash?: string;
            gradingSandboxId?: string;
            failureReason?: string;
            /** @enum {unknown} */
            traceTrust: "none" | "platform-hmac";
            platformExecutionId?: string;
            graderResult?: components["schemas"]["GraderResult"];
        };
        ScoreSchema: {
            passingScore: string;
            minScore?: string;
            maxScore?: string;
            scoreScale: number;
            scoreUnit?: string;
        };
        GraderResult: {
            score: string;
            passed?: boolean;
            feedback: string;
            metadata: Record<string, never>;
        };
        RequiredFunction: {
            name: string;
            argumentsSchema: Record<string, never>;
            outputSchema: Record<string, never>;
            required: boolean;
            minCalls?: number;
            maxCalls?: number;
            order?: Record<string, never>;
        };
        PublicFunction: {
            name: string;
            inputSchema: Record<string, never>;
            outputSchema: Record<string, never>;
        };
        PublicExample: {
            functionName: string;
            input: unknown;
            output: unknown;
        };
        PublicChallengeSpec: {
            problemDescription: string;
            successCriteria: string;
            /** @enum {unknown} */
            language: "typescript" | "javascript" | "python";
            runtimeVersion: string;
            entrypoint: string;
            requiredFunctions: components["schemas"]["PublicFunction"][];
            submissionFormat: string;
            allowedDependencies: string[];
            scoring: components["schemas"]["ScoreSchema"];
            examples: components["schemas"]["PublicExample"][];
            starterCode?: string;
            /** @constant */
            documentationConfirmed: true;
        };
        AgentSubmission: {
            code: string;
            /** @enum {unknown} */
            language: "typescript" | "javascript" | "python";
            finalOutput: unknown;
            artifacts?: unknown[];
        };
        GraderPreflight: {
            /** @enum {unknown} */
            language: "typescript" | "javascript" | "python";
            runtimeVersion: string;
            /** @enum {unknown} */
            entrypoint?: "default" | "grade";
            graderSource?: string;
            graderSourceBase64?: string;
            graderFileName?: string;
            graderConfig?: Record<string, never>;
            dependencies?: string[];
            validationSample?: components["schemas"]["AgentSubmission"];
            requiredFunctions?: components["schemas"]["RequiredFunction"][];
            submissionSchema?: Record<string, never>;
            scoring: components["schemas"]["ScoreSchema"];
        };
        CreateChallenge: components["schemas"]["GraderPreflight"] & {
            title: string;
            description: string;
            tags: string[];
            agentContext: string;
            rewardWei: string;
            maxSubmissions: number;
            /** Format: date-time */
            deadline: string;
            /** @enum {integer} */
            chainId: 10143;
            publicSpec: components["schemas"]["PublicChallengeSpec"];
        };
        SignedSubmission: {
            payload: components["schemas"]["AgentSubmission"];
            nonce: string;
            signature: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
