export type ChallengeStatus = "funding" | "live" | "settled" | "expired" | "refunded";
export type SubmissionStatus = "UPLOADED" | "QUEUED" | "GRADING" | "GRADED" | "SETTLEMENT_PENDING" | "FINALIZED" | "PAID" | "NO_PAYOUT" | "FAILED" | "UNEVALUABLE" | "GRADER_ERROR" | "TIMEOUT";
export type GradingOutcome = "SCORED" | "UNEVALUABLE" | "GRADER_ERROR" | "GRADING_TIMEOUT";
export type GraderLanguage = "typescript" | "javascript" | "python";
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type RequiredFunction = { name: string; argumentsSchema: Record<string, unknown>; outputSchema: Record<string, unknown>; required: boolean; minCalls?: number; maxCalls?: number; order?: { after?: string[]; before?: string[] } };
export type TrustedFunctionCall = { name: string; arguments: JsonValue; output: JsonValue; sequence: number; occurredAt: string; runtimeId: string };
/** The only value custom grader code receives. functionCalls is populated by the trusted runtime/worker, never a client request. */
export type GraderInput = { submittedCode: { source: string; language: GraderLanguage }; agentFinalOutput: JsonValue; trustedFunctionCallTrace: TrustedFunctionCall[]; producedArtifacts: { name: string; mediaType: string; sha256: string; bytes: number; content?: JsonValue }[]; challengeRequirements: { requiredFunctions: RequiredFunction[]; submissionSchema: Record<string, unknown> }; scoreSchema: ScoreSchema; executionMetadata: { submissionId: string; challengeId: string; submissionHash: string; receivedAt: string; runtime: string } };
export type GraderResult = { score: string; passed?: boolean; feedback: string; metadata: Record<string, JsonValue> };
export type GraderErrorCode = "GRADER_COMPILE_FAILURE" | "GRADER_MISSING_ENTRYPOINT" | "GRADER_INVALID_RESULT" | "GRADER_TIMEOUT" | "GRADER_SANDBOX_VIOLATION" | "GRADER_SCORE_OUT_OF_RANGE" | "SUBMISSION_INVALID" | "GRADER_PREFLIGHT_FAILED";
export type ScoreSchema = { passingScore: string; minScore?: string; maxScore?: string; scoreScale: number; scoreUnit?: string };
export type PublicFunction = { name: string; inputSchema: Record<string, unknown>; outputSchema: Record<string, unknown> };
export type PublicExample = { functionName: string; input: JsonValue; output: JsonValue };
export type PublicChallengeSpec = { problemDescription: string; successCriteria: string; language: GraderLanguage; runtimeVersion: string; entrypoint: string; requiredFunctions: PublicFunction[]; submissionFormat: string; allowedDependencies: string[]; scoring: ScoreSchema; examples: PublicExample[]; starterCode?: string; documentationConfirmed: true };
export type PrivateGrader = { language: GraderLanguage; runtimeVersion: string; entrypoint: "default" | "grade"; sourceBase64: string; sourceBytes: number; objectKey: string; config: Record<string, unknown>; dependencies: string[]; checksum: string; version: number; commitment: string };
/** Private execution metadata sent only to the isolated worker. Source bytes remain in private object storage. */
export type WorkerGrader = Omit<PrivateGrader, "sourceBase64">;
export type Challenge = { id: string; title: string; description: string; tags: string[]; reward: string; passingScore: string; minScore?: string; maxScore?: string; scoreScale: number; scoreUnit?: string; submissions: number; maxSubmissions: number; deadline: string; requester: string; status: ChallengeStatus; context: string; format: string; graderType: string; chainId: number; contractAddress?: string; graderCommitment?: string; transactionHash?: string; refundedTransactionHash?: string };
export type ChallengeRecord = Challenge & { companyId: string; onchainChallengeId?: string; authorizedBackend: string; grader: PrivateGrader; graderVersion: number; requiredFunctions: RequiredFunction[]; submissionSchema: Record<string, unknown>; publicSpec: PublicChallengeSpec; preflightedAt: string; rewardWei: string; passingScoreScaled: string; minScoreScaled?: string; maxScoreScaled?: string; deploymentBlock?: number; createdAt: string; indexed: boolean; paid: boolean; refunded: boolean };
export type Company = { id: string; privySubject: string; createdAt: string; updatedAt: string };
export type Submission = { id: string; challengeId: string; agentWallet: string; payoutAddress: string; objectKey: string; submissionHash: string; status: SubmissionStatus; createdAt: string; scoreScaled?: string; score?: string; graderResult?: GraderResult; gradingSandboxId?: string; outcome?: GradingOutcome; jobId?: string; graderCommitment?: string; graderVersion?: number; settlementNonce?: string; settlementExpiry?: string; settlementSignature?: string; settlementBroadcastAt?: string; transactionHash?: string; finalizedEventId?: string; failureReason?: string; traceTrust: "none" | "platform-hmac"; platformExecutionId?: string };
export type GradingJob = { id: string; submissionId: string; challengeId: string; submissionHash: string; agentWallet: string; graderCommitment: string; graderVersion: number; attempts: number; status: "queued" | "running" | "complete" | "retry" | "failed"; createdAt: string; claimedAt?: string; grader?: WorkerGrader; solutionObjectKey?: string; requiredFunctions?: RequiredFunction[]; submissionSchema?: Record<string, unknown>; scoreSchema?: ScoreSchema };
export type WalletNonce = { nonce: string; purpose: "agent_submission"; challengeId: string; expiresAt: string; usedAt?: string };
export type IndexerCheckpoint = { chainId: number; contractAddress: string; blockNumber: number; blockHash: string; updatedAt: string };
export const passes = (scoreScaled: bigint, passingScoreScaled: bigint) => scoreScaled >= passingScoreScaled;
export { sha256Hex, canonicalizeSource, commitment, parseScaledScore } from "./crypto";
