import { createServer } from "node:http";
import { createHmac, randomUUID, timingSafeEqual } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { createChallengeSchema, submitSolutionSchema, walletNonceSchema, workerResultSchema } from "@verity/api-contract";
import { commitment, sha256Hex } from "@verity/domain";
import type { ChallengeRecord, GradingJob, Submission } from "@verity/domain";
import { JsonFileStore } from "@verity/adapters";
import { createPublicClient, createWalletClient, http, keccak256, stringToHex, defineChain, encodeDeployData, recoverMessageAddress, parseEventLogs } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { authenticateCompany, AuthError, requireCompanyOwnership } from "./auth";

const port = Number(process.env.API_PORT ?? 4000); const store = new JsonFileStore(); const objectDir = process.env.VERITY_OBJECT_DIR ?? ".verity/objects";
const rpcUrl = process.env.RPC_URL ?? "http://127.0.0.1:8545"; const backendKey = (process.env.SETTLEMENT_PRIVATE_KEY ?? "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80") as `0x${string}`; const backend = privateKeyToAccount(backendKey);
const chain = defineChain({ id: Number(process.env.CHAIN_ID ?? 31337), name: "local-monad", nativeCurrency: { name: "MON", symbol: "MON", decimals: 18 }, rpcUrls: { default: { http: [rpcUrl] } } });
const artifact = JSON.parse(readFileSync(resolve(process.cwd(), "../../artifacts/contracts/ChallengeEscrow.json"), "utf8")); const publicClient = createPublicClient({ chain, transport: http(rpcUrl) }); const walletClient = createWalletClient({ account: backend, chain, transport: http(rpcUrl) });
const workerSecret = process.env.WORKER_SHARED_SECRET ?? "";
const publicChallenge = (c: ChallengeRecord) => { const { companyId, authorizedBackend, graderSourceKey, graderVersion, rewardWei, deploymentBlock, indexed, paid, ...publicFields } = c; return publicFields; };
const send = (res: import("node:http").ServerResponse, status: number, body: unknown) => { res.writeHead(status, { "content-type": "application/json" }); res.end(JSON.stringify(body)); };
async function readBody(req: import("node:http").IncomingMessage) { let raw = ""; for await (const chunk of req) raw += chunk; return { raw, value: JSON.parse(raw || "{}") }; }
const walletMessage = (challengeId: string, nonce: string, expiry: string) => `Verity agent submission\nchallenge:${challengeId}\nnonce:${nonce}\nexpires:${expiry}`;
const hmac = (body: string) => createHmac("sha256", workerSecret).update(body).digest("hex");
const hasWorkerAuth = (req: import("node:http").IncomingMessage, raw: string) => { const got = req.headers["x-verity-worker-signature"]; if (!workerSecret || typeof got !== "string") return false; const expected = hmac(raw); return got.length === expected.length && timingSafeEqual(Buffer.from(got), Buffer.from(expected)); };
async function finalize(submission: Submission, challenge: ChallengeRecord) {
  if (!challenge.contractAddress || !challenge.onchainChallengeId || !submission.outcome || submission.scoreBasisPoints === undefined) throw new Error("settlement_not_ready");
  const expiry = BigInt(Math.min(Math.floor(Date.now() / 1000) + 300, Math.floor(new Date(challenge.deadline).getTime() / 1000)));
  const nonce = BigInt(`0x${sha256Hex(submission.id).slice(0, 16)}`); const submissionId = keccak256(stringToHex(submission.id));
  const message = { chainId: BigInt(chain.id), verifyingContract: challenge.contractAddress as `0x${string}`, challengeId: challenge.onchainChallengeId as `0x${string}`, submissionId, submissionHash: submission.submissionHash as `0x${string}`, agent: submission.payoutAddress as `0x${string}`, score: submission.scoreBasisPoints, outcome: keccak256(stringToHex(submission.outcome)), graderCommitment: challenge.graderCommitment as `0x${string}`, graderVersion: challenge.graderVersion, nonce, expiry };
  const signature = await backend.signTypedData({ domain: { name: "Verity ChallengeEscrow", version: "1", chainId: chain.id, verifyingContract: challenge.contractAddress as `0x${string}` }, types: { Settlement: [{ name: "chainId", type: "uint256" }, { name: "verifyingContract", type: "address" }, { name: "challengeId", type: "bytes32" }, { name: "submissionId", type: "bytes32" }, { name: "submissionHash", type: "bytes32" }, { name: "agent", type: "address" }, { name: "score", type: "uint16" }, { name: "outcome", type: "bytes32" }, { name: "graderCommitment", type: "bytes32" }, { name: "graderVersion", type: "uint32" }, { name: "nonce", type: "uint256" }, { name: "expiry", type: "uint256" }] }, primaryType: "Settlement", message });
  submission.status = "SETTLEMENT_PENDING"; submission.settlementNonce = nonce.toString(); submission.settlementExpiry = expiry.toString(); submission.settlementSignature = signature; await store.saveSubmission(submission);
  const hash = await walletClient.writeContract({ address: challenge.contractAddress as `0x${string}`, abi: artifact.abi, functionName: "finalize", args: [submissionId, submission.submissionHash, submission.payoutAddress, submission.scoreBasisPoints, message.outcome, nonce, expiry, signature] });
  submission.transactionHash = hash; await store.saveSubmission(submission); // Indexer is the sole final-state writer.
}
async function main() { await store.load(); await mkdir(objectDir, { recursive: true });
  const server = createServer(async (req, res) => { try { const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`); const p = url.pathname.split("/").filter(Boolean); const { raw, value } = req.method === "GET" ? { raw: "", value: {} } : await readBody(req);
    if (req.method === "GET" && url.pathname === "/health") return send(res, 200, { ok: true, mode: "real" });
    if (req.method === "GET" && url.pathname === "/api/challenges") return send(res, 200, { challenges: [...store.challenges.values()].filter(c => c.indexed).map(publicChallenge) });
    if (req.method === "GET" && p[0] === "api" && p[1] === "submissions" && p[2]) { const s = await store.getSubmission(p[2]); return s ? send(res, 200, s) : send(res, 404, { error: "submission_not_found" }); }
    if (req.method === "GET" && p[0] === "api" && p[1] === "challenges" && p[2]) { const c = await store.getChallenge(p[2]); return c ? send(res, 200, publicChallenge(c)) : send(res, 404, { error: "challenge_not_found" }); }
    if (req.method === "POST" && url.pathname === "/api/challenges") { const auth = await authenticateCompany(req, store); const input = createChallengeSchema.parse(value); const source = input.graderSource ?? Buffer.from(input.graderSourceBase64!, "base64").toString("utf8"); if (!source.includes("export default")) return send(res, 400, { error: "invalid_grader_source" }); const id = randomUUID(); const key = `graders/${id}.ts`; await writeFile(join(objectDir, key.replace("/", "-")), source, { mode: "0600" }); const c: ChallengeRecord = { id, companyId: auth.company.id, title: input.title, description: input.description, tags: input.tags, reward: `${input.rewardWei} wei`, minimumScore: input.minimumScore, submissions: 0, maxSubmissions: input.maxSubmissions, deadline: input.deadline, requester: auth.company.id, status: "funding", context: input.agentContext, format: "JSON", graderType: input.graderFileName ?? "TypeScript private grader", chainId: input.chainId, authorizedBackend: backend.address, graderSourceKey: key, graderVersion: 1, graderCommitment: commitment(source, input.sandboxConfig), rewardWei: input.rewardWei, createdAt: new Date().toISOString(), indexed: false }; await store.saveChallenge(c); const deployment = encodeDeployData({ abi: artifact.abi, bytecode: artifact.bytecode, args: [keccak256(stringToHex(c.id)), c.minimumScore, c.maxSubmissions, BigInt(Math.floor(new Date(c.deadline).getTime() / 1000)), backend.address, c.graderCommitment as `0x${string}`, c.graderVersion] }); return send(res, 201, { challenge: publicChallenge(c), walletTransaction: { data: deployment, value: c.rewardWei, chainId: c.chainId }, next: "company_wallet_deploy_and_fund" }); }
    if (req.method === "POST" && p[0] === "api" && p[1] === "challenges" && p[3] === "funding-confirmed") { const auth = await authenticateCompany(req, store); const c = await store.getChallenge(p[2]); if (!c) return send(res, 404, { error: "challenge_not_found" }); requireCompanyOwnership(c.companyId!, auth.company.id); const receipt = await publicClient.getTransactionReceipt({ hash: value.transactionHash as `0x${string}` }); if (receipt.status !== "success" || !receipt.contractAddress) return send(res, 409, { error: "funding_not_confirmed" }); const events: any[] = parseEventLogs({ abi: artifact.abi, logs: receipt.logs }); const created = events.find(e => e.eventName === "ChallengeCreated" && e.args.challengeId?.toLowerCase() === keccak256(stringToHex(c.id)).toLowerCase()); if (!created) return send(res, 400, { error: "wrong_challenge_deployment" }); c.contractAddress = receipt.contractAddress; c.onchainChallengeId = created.args.challengeId; c.deploymentBlock = Number(receipt.blockNumber); await store.saveChallenge(c); return send(res, 202, { challenge: c, status: "AWAITING_INDEX" }); }
    if (req.method === "POST" && p[0] === "api" && p[1] === "challenges" && p[3] === "wallet-nonces") { const c = await store.getChallenge(p[2]); if (!c || !c.indexed) return send(res, 409, { error: "challenge_not_live" }); walletNonceSchema.parse({ challengeId: c.id }); const nonce = randomUUID(); const expiresAt = new Date(Date.now() + 5 * 60_000).toISOString(); await store.saveWalletNonce({ nonce, purpose: "agent_submission", challengeId: c.id, expiresAt }); return send(res, 201, { nonce, expiresAt, message: walletMessage(c.id, nonce, expiresAt) }); }
    if (req.method === "POST" && p[0] === "api" && p[1] === "challenges" && p[3] === "submissions") { const c = await store.getChallenge(p[2]); if (!c || !c.indexed) return send(res, 409, { error: "challenge_not_live" }); if (Date.now() > new Date(c.deadline).getTime()) return send(res, 409, { error: "deadline_expired" }); if (await store.countForChallenge(c.id) >= c.maxSubmissions) return send(res, 409, { error: "submission_limit" }); const input = submitSolutionSchema.parse(value); const nonce = await store.getWalletNonce(input.nonce); if (!nonce || nonce.usedAt || nonce.challengeId !== c.id || Date.now() > new Date(nonce.expiresAt).getTime()) return send(res, 401, { error: "invalid_or_replayed_wallet_nonce" }); const agent = await recoverMessageAddress({ message: walletMessage(c.id, nonce.nonce, nonce.expiresAt), signature: input.signature as `0x${string}` }); nonce.usedAt = new Date().toISOString(); await store.saveWalletNonce(nonce); const id = randomUUID(); const bytes = Buffer.from(JSON.stringify(input.payload)); const submissionHash = `0x${sha256Hex(bytes)}`; const objectKey = `submissions/${id}.json`; await writeFile(join(objectDir, objectKey.replace("/", "-")), bytes, { mode: 0o600 }); const job: GradingJob = { id: randomUUID(), submissionId: id, challengeId: c.id, submissionHash, agentWallet: agent, graderCommitment: c.graderCommitment!, graderVersion: c.graderVersion, attempts: 1, status: "queued", createdAt: new Date().toISOString() }; const s: Submission = { id, challengeId: c.id, agentWallet: agent, payoutAddress: input.payoutAddress ?? agent, objectKey, submissionHash, status: "QUEUED", createdAt: new Date().toISOString(), jobId: job.id, graderCommitment: c.graderCommitment, graderVersion: c.graderVersion }; await store.saveSubmission(s); await store.enqueue(job); return send(res, 202, { submission: s }); }
if (req.method === "POST" && url.pathname === "/internal/jobs/claim") { if (!hasWorkerAuth(req, raw)) return send(res, 401, { error: "worker_unauthorized" }); const job = await store.dequeue(); if (!job) return send(res, 204, {}); job.status = "running"; job.claimedAt = new Date().toISOString(); await store.flush(); const s = await store.getSubmission(job.submissionId); const c = s && await store.getChallenge(s.challengeId); if (!s || !c) return send(res, 409, { error: "job_missing_records" }); job.graderSourceKey = c.graderSourceKey; job.solutionObjectKey = s.objectKey; await store.flush(); return send(res, 200, { job }); }
    if (req.method === "POST" && url.pathname === "/internal/worker-results") { if (!hasWorkerAuth(req, raw)) return send(res, 401, { error: "worker_unauthorized" }); const result = workerResultSchema.parse(value); const job = store.jobs.find(j => j.id === result.jobId); const s = await store.getSubmission(result.submissionId); const c = await store.getChallenge(result.challengeId); if (!job || !s || !c || job.status !== "running" || job.submissionId !== s.id || job.attempts !== result.attempt || s.submissionHash !== result.submissionHash || s.agentWallet.toLowerCase() !== result.agentWallet.toLowerCase() || c.graderCommitment !== result.graderCommitment || c.graderVersion !== result.graderVersion) return send(res, 409, { error: "forged_stale_or_mismatched_worker_result" }); job.status = "complete"; s.outcome = result.outcome; s.scoreBasisPoints = result.scoreBasisPoints; s.status = result.outcome === "UNEVALUABLE" ? "UNEVALUABLE" : result.outcome === "GRADER_ERROR" ? "GRADER_ERROR" : result.outcome === "GRADING_TIMEOUT" ? "TIMEOUT" : "GRADED"; await store.saveSubmission(s); await store.flush(); if (result.outcome === "SCORED") await finalize(s, c); return send(res, 202, { submission: s }); }
    return send(res, 404, { error: "not_found" });
  } catch (e) { if (e instanceof AuthError) return send(res, e.status, { error: e.code }); return send(res, 400, { error: e instanceof Error ? e.message : "bad_request" }); } }); server.listen(port, () => console.log(`Verity API listening on http://localhost:${port}`)); }
void main();
