import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createPublicClient, createWalletClient, http, keccak256, stringToHex, parseEther, getContractAddress, defineChain } from "viem";
import { privateKeyToAccount } from "viem/accounts";
const key = process.env.DEPLOYER_PRIVATE_KEY ?? "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const rpcUrl = process.env.RPC_URL ?? "http://127.0.0.1:8545"; const account = privateKeyToAccount(key);
const chain = defineChain({ id: Number(process.env.CHAIN_ID ?? 31337), name: "local-monad", nativeCurrency: { name: "MON", symbol: "MON", decimals: 18 }, rpcUrls: { default: { http: [rpcUrl] } } });
const artifact = JSON.parse(await readFile("artifacts/contracts/ChallengeEscrow.json", "utf8")); const publicClient = createPublicClient({ chain, transport: http(rpcUrl) }); const wallet = createWalletClient({ account, chain, transport: http(rpcUrl) });
const existing = await readFile(".verity/deployment.json", "utf8").then(JSON.parse).catch(() => undefined); if (existing && existing.chainId === chain.id && await publicClient.getBytecode({ address: existing.address })) { console.log(JSON.stringify(existing)); process.exit(0); }
const deadline = BigInt(Math.floor(Date.now() / 1000) + 7 * 86400); const hash = await wallet.deployContract({ abi: artifact.abi, bytecode: artifact.bytecode, args: [keccak256(stringToHex("local-warehouse")), 8500, 40, deadline, account.address, keccak256(stringToHex("warehouse-grader")), 1], value: parseEther("1") }); const receipt = await publicClient.waitForTransactionReceipt({ hash });
const deployment = { chainId: chain.id, rpcUrl, address: receipt.contractAddress, deploymentBlock: Number(receipt.blockNumber), authorizedBackend: account.address, abiPath: "artifacts/contracts/ChallengeEscrow.json", transactionHash: hash }; await mkdir(".verity", { recursive: true }); await writeFile(".verity/deployment.json", JSON.stringify(deployment, null, 2)); console.log(JSON.stringify(deployment));
